<a href="https://colab.research.google.com/github/Thanveerahmedshaik/MachineLearning/blob/main/OrdinalEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/customer.csv')

In [67]:
df.head()



age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [68]:
# #data is of customers
# age
# gender
# when the customer purchased a product another
# product is recommended did the customer purchase the another
# product or not purchased column tells that



In [69]:
df = df.iloc[:,2:]

In [70]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

**Ordinal Encoding**

In [71]:
from sklearn.model_selection import train_test_split


x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,:2],
                                                 df.iloc[:,-1],test_size=0.2)

In [72]:

x_train

review education
16     Poor        UG
31     Poor    School
41     Good        PG
15     Poor        UG
45     Poor        PG
0   Average    School
49     Good        UG
1      Poor        UG
30  Average        UG
6      Good    School
44  Average        UG
33     Good        PG
38     Good    School
10     Good        UG
21  Average        PG
2      Good        PG
23     Good    School
8   Average        UG
5   Average    School
28     Poor    School
27     Poor        PG
32  Average        UG
36     Good        UG
24  Average        PG
7      Poor    School
26     Poor        PG
14     Poor        PG
17     Poor        UG
13  Average    School
19     Poor        PG
40     Good    School
4   Average        UG
34  Average    School
18     Good    School
47     Good        PG
37  Average        PG
9      Good        UG
25     Good    School
29  Average        UG
48     Good        UG

In [73]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [74]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [75]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [76]:
x_train

array([[0., 1.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 1.]])

In [77]:
x_test

array([[1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [2., 1.]])

In [78]:
x_train = pd.DataFrame(x_train,columns= df.columns[:2])
x_test = pd.DataFrame(x_test,columns= df.columns[:2])

In [79]:
x_train

review  education
0      0.0        1.0
1      0.0        0.0
2      2.0        2.0
3      0.0        1.0
4      0.0        2.0
5      1.0        0.0
6      2.0        1.0
7      0.0        1.0
8      1.0        1.0
9      2.0        0.0
10     1.0        1.0
11     2.0        2.0
12     2.0        0.0
13     2.0        1.0
14     1.0        2.0
15     2.0        2.0
16     2.0        0.0
17     1.0        1.0
18     1.0        0.0
19     0.0        0.0
20     0.0        2.0
21     1.0        1.0
22     2.0        1.0
23     1.0        2.0
24     0.0        0.0
25     0.0        2.0
26     0.0        2.0
27     0.0        1.0
28     1.0        0.0
29     0.0        2.0
30     2.0        0.0
31     1.0        1.0
32     1.0        0.0
33     2.0        0.0
34     2.0        2.0
35     1.0        2.0
36     2.0        1.0
37     2.0        0.0
38     1.0        1.0
39     2.0        1.0

In [80]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [81]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [82]:
le.fit(y_train)

LabelEncoder()

In [90]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [83]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [84]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1])

In [85]:
y_test

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1])

In [88]:
y_train = pd.DataFrame(y_train,columns= df.columns[2:])
y_test = pd.DataFrame(y_test,columns= df.columns[2:])

In [89]:
y_train

purchased
0           1
1           1
2           1
3           0
4           1
5           0
6           0
7           0
8           0
9           0
10          0
11          1
12          0
13          1
14          0
15          0
16          0
17          0
18          1
19          0
20          0
21          1
22          1
23          1
24          1
25          0
26          1
27          1
28          0
29          1
30          0
31          0
32          0
33          0
34          1
35          1
36          1
37          0
38          1
39          1